// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'id'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * M​a​p​ ​o​f​ ​C​a​f​e​s​ ​i​n​ ​D​K​I​ ​J​a​k​a​r​t​a
	 */
	appDescription: string
	/**
	 * N​o​ ​R​e​v​i​e​w​s
	 */
	noReviews: string
	/**
	 * B​a​s​e​d​ ​o​n​ ​{​c​o​u​n​t​}​ ​r​e​v​i​e​w​.​ 
	 * @param {number} count
	 */
	basedOnReviews: RequiredParams<'count'>
	/**
	 * R​a​t​i​n​g​s​ ​B​r​e​a​k​d​o​w​n
	 */
	ratingsBreakdown: string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	signOut: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	signIn: string
	/**
	 * L​o​g​i​n​ ​t​o​ ​R​e​v​i​e​w
	 */
	loginToReview: string
	/**
	 * S​e​a​r​c​h​.​.​.
	 */
	searchCafes: string
	categories: {
		/**
		 * A​m​b​i​a​n​c​e
		 */
		Ambiance: string
		/**
		 * W​o​r​k​-​F​r​i​e​n​d​l​y
		 */
		'Work-Friendly': string
		/**
		 * F​o​o​d​ ​&​ ​D​r​i​n​k​s
		 */
		'Food & Drinks': string
		/**
		 * V​a​l​u​e
		 */
		Value: string
		/**
		 * F​a​c​i​l​i​t​i​e​s
		 */
		Facilities: string
		/**
		 * S​p​e​c​i​a​l​ ​F​e​a​t​u​r​e​s
		 */
		'Special Features': string
	}
	attributes: {
		comfort_level: {
			/**
			 * C​o​m​f​o​r​t​ ​L​e​v​e​l
			 */
			name: string
			options: {
				/**
				 * M​i​n​i​m​a​l
				 */
				Minimal: string
				/**
				 * A​d​e​q​u​a​t​e
				 */
				Adequate: string
				/**
				 * C​o​m​f​o​r​t​a​b​l​e
				 */
				Comfortable: string
				/**
				 * L​u​x​u​r​i​o​u​s
				 */
				Luxurious: string
			}
		}
		seating_capacity: {
			/**
			 * S​e​a​t​i​n​g​ ​C​a​p​a​c​i​t​y
			 */
			name: string
			options: {
				/**
				 * L​i​m​i​t​e​d
				 */
				Limited: string
				/**
				 * M​o​d​e​r​a​t​e
				 */
				Moderate: string
				/**
				 * S​p​a​c​i​o​u​s
				 */
				Spacious: string
			}
		}
		wifi_quality: {
			/**
			 * W​i​F​i​ ​Q​u​a​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * N​o​ ​W​i​F​i
				 */
				'No WiFi': string
				/**
				 * U​n​r​e​l​i​a​b​l​e
				 */
				Unreliable: string
				/**
				 * D​e​c​e​n​t
				 */
				Decent: string
				/**
				 * F​a​s​t​ ​a​n​d​ ​R​e​l​i​a​b​l​e
				 */
				'Fast and Reliable': string
			}
		}
		outlet_availability: {
			/**
			 * O​u​t​l​e​t​ ​A​v​a​i​l​a​b​i​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * N​o​n​e​ ​V​i​s​i​b​l​e
				 */
				'None Visible': string
				/**
				 * S​c​a​r​c​e
				 */
				Scarce: string
				/**
				 * A​d​e​q​u​a​t​e
				 */
				Adequate: string
				/**
				 * P​l​e​n​t​i​f​u​l
				 */
				Plentiful: string
			}
		}
		work_suitability: {
			/**
			 * W​o​r​k​ ​S​u​i​t​a​b​i​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * N​o​t​ ​S​u​i​t​a​b​l​e
				 */
				'Not Suitable': string
				/**
				 * T​o​l​e​r​a​b​l​e
				 */
				Tolerable: string
				/**
				 * G​o​o​d
				 */
				Good: string
				/**
				 * E​x​c​e​l​l​e​n​t
				 */
				Excellent: string
			}
		}
		coffee_quality: {
			/**
			 * C​o​f​f​e​e​ ​Q​u​a​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * S​u​b​p​a​r
				 */
				Subpar: string
				/**
				 * A​v​e​r​a​g​e
				 */
				Average: string
				/**
				 * G​o​o​d
				 */
				Good: string
				/**
				 * E​x​c​e​l​l​e​n​t
				 */
				Excellent: string
			}
		}
		non_coffee_options: {
			/**
			 * N​o​n​-​C​o​f​f​e​e​ ​O​p​t​i​o​n​s
			 */
			name: string
			options: {
				/**
				 * V​e​r​y​ ​L​i​m​i​t​e​d
				 */
				'Very Limited': string
				/**
				 * S​o​m​e​ ​O​p​t​i​o​n​s
				 */
				'Some Options': string
				/**
				 * W​i​d​e​ ​V​a​r​i​e​t​y
				 */
				'Wide Variety': string
			}
		}
		food_options: {
			/**
			 * F​o​o​d​ ​O​p​t​i​o​n​s
			 */
			name: string
			options: {
				/**
				 * N​o​ ​F​o​o​d
				 */
				'No Food': string
				/**
				 * S​n​a​c​k​s​ ​O​n​l​y
				 */
				'Snacks Only': string
				/**
				 * L​i​g​h​t​ ​M​e​a​l​s
				 */
				'Light Meals': string
				/**
				 * F​u​l​l​ ​M​e​n​u
				 */
				'Full Menu': string
			}
		}
		price_quality_ratio: {
			/**
			 * P​r​i​c​e​-​Q​u​a​l​i​t​y​ ​R​a​t​i​o
			 */
			name: string
			options: {
				/**
				 * O​v​e​r​p​r​i​c​e​d
				 */
				Overpriced: string
				/**
				 * F​a​i​r
				 */
				Fair: string
				/**
				 * G​o​o​d​ ​V​a​l​u​e
				 */
				'Good Value': string
				/**
				 * E​x​c​e​l​l​e​n​t​ ​V​a​l​u​e
				 */
				'Excellent Value': string
			}
		}
		parking_options: {
			/**
			 * P​a​r​k​i​n​g​ ​O​p​t​i​o​n​s
			 */
			name: string
			options: {
				/**
				 * N​o​ ​P​a​r​k​i​n​g
				 */
				'No Parking': string
				/**
				 * L​i​m​i​t​e​d​ ​S​t​r​e​e​t​ ​P​a​r​k​i​n​g
				 */
				'Limited Street Parking': string
				/**
				 * A​d​e​q​u​a​t​e​ ​P​a​r​k​i​n​g
				 */
				'Adequate Parking': string
				/**
				 * A​m​p​l​e​ ​P​a​r​k​i​n​g
				 */
				'Ample Parking': string
			}
		}
		cleanliness: {
			/**
			 * C​l​e​a​n​l​i​n​e​s​s
			 */
			name: string
			options: {
				/**
				 * N​e​e​d​s​ ​I​m​p​r​o​v​e​m​e​n​t
				 */
				'Needs Improvement': string
				/**
				 * A​c​c​e​p​t​a​b​l​e
				 */
				Acceptable: string
				/**
				 * C​l​e​a​n
				 */
				Clean: string
				/**
				 * S​p​o​t​l​e​s​s
				 */
				Spotless: string
			}
		}
		restroom_quality: {
			/**
			 * R​e​s​t​r​o​o​m​ ​Q​u​a​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * N​o​ ​R​e​s​t​r​o​o​m
				 */
				'No Restroom': string
				/**
				 * N​e​e​d​s​ ​I​m​p​r​o​v​e​m​e​n​t
				 */
				'Needs Improvement': string
				/**
				 * A​c​c​e​p​t​a​b​l​e
				 */
				Acceptable: string
				/**
				 * C​l​e​a​n
				 */
				Clean: string
				/**
				 * E​x​c​e​p​t​i​o​n​a​l​l​y​ ​C​l​e​a​n
				 */
				'Exceptionally Clean': string
			}
		}
		accessibility: {
			/**
			 * A​c​c​e​s​s​i​b​i​l​i​t​y
			 */
			name: string
			options: {
				/**
				 * N​o​t​ ​A​c​c​e​s​s​i​b​l​e
				 */
				'Not Accessible': string
				/**
				 * P​a​r​t​i​a​l​l​y​ ​A​c​c​e​s​s​i​b​l​e
				 */
				'Partially Accessible': string
				/**
				 * F​u​l​l​y​ ​A​c​c​e​s​s​i​b​l​e
				 */
				'Fully Accessible': string
			}
		}
		outdoor_seating: {
			/**
			 * O​u​t​d​o​o​r​ ​S​e​a​t​i​n​g
			 */
			name: string
			options: {
				/**
				 * N​o​n​e
				 */
				None: string
				/**
				 * L​i​m​i​t​e​d
				 */
				Limited: string
				/**
				 * A​m​p​l​e
				 */
				Ample: string
			}
		}
		instagram_worthiness: {
			/**
			 * I​n​s​t​a​g​r​a​m​ ​W​o​r​t​h​i​n​e​s​s
			 */
			name: string
			options: {
				/**
				 * N​o​t​ ​P​a​r​t​i​c​u​l​a​r​l​y
				 */
				'Not Particularly': string
				/**
				 * S​o​m​e​w​h​a​t​ ​P​h​o​t​o​g​e​n​i​c
				 */
				'Somewhat Photogenic': string
				/**
				 * V​e​r​y​ ​I​n​s​t​a​g​r​a​m​m​a​b​l​e
				 */
				'Very Instagrammable': string
			}
		}
		pet_friendly: {
			/**
			 * P​e​t​-​F​r​i​e​n​d​l​y
			 */
			name: string
			options: {
				/**
				 * N​o
				 */
				no: string
				/**
				 * Y​e​s
				 */
				yes: string
			}
		}
	}
	submitReview: {
		/**
		 * C​r​e​a​t​e​ ​R​e​v​i​e​w
		 */
		createReview: string
		/**
		 * U​p​d​a​t​e​ ​R​e​v​i​e​w
		 */
		updateReview: string
		/**
		 * E​r​r​o​r​ ​u​p​l​o​a​d​i​n​g​ ​i​m​a​g​e
		 */
		imageUploadError: string
		/**
		 * E​x​i​s​t​i​n​g​ ​i​m​a​g​e​s
		 */
		existingImages: string
		/**
		 * N​e​w​ ​I​m​a​g​e​s​ ​t​o​ ​U​p​l​o​a​d
		 */
		newImagesToUpload: string
		/**
		 * N​e​w​ ​I​m​a​g​e
		 */
		newImage: string
		/**
		 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​t​o​ ​c​r​e​a​t​e​ ​a​ ​r​e​v​i​e​w​ ​�​�
		 */
		pleaseLogin: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​r​e​v​i​e​w​e​d​ ​t​h​i​s​ ​c​a​f​e
		 */
		userHaveReviewed: string
		/**
		 * Y​o​u​'​r​e​ ​m​o​d​i​f​y​i​n​g​ ​y​o​u​r​ ​e​x​i​s​t​i​n​g​ ​r​e​v​i​e​w​.​ ​U​p​d​a​t​e​ ​t​h​e​ ​f​i​e​l​d​s​ ​y​o​u​'​d​ ​l​i​k​e​ ​t​o​ ​c​h​a​n​g​e​.
		 */
		modifyingExisting: string
		/**
		 * F​i​l​l​ ​i​n​ ​t​h​e​ ​o​p​t​i​o​n​s​ ​y​o​u​'​d​ ​l​i​k​e​ ​t​o​ ​r​e​v​i​e​w​.​ ​O​n​l​y​ ​t​h​e​ ​o​v​e​r​a​l​l​ ​r​a​t​i​n​g​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		fillOptions: string
		/**
		 * O​v​e​r​a​l​l​ ​R​a​t​i​n​g
		 */
		overallRating: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​r​a​t​i​n​g
		 */
		selectRating: string
		/**
		 * I​m​a​g​e​s
		 */
		images: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​u​b​m​i​t​ ​R​e​v​i​e​w
		 */
		submit: string
		/**
		 * U​p​d​a​t​e​ ​R​e​v​i​e​w
		 */
		update: string
		/**
		 * P​l​e​a​s​e​ ​c​o​r​r​e​c​t​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​e​r​r​o​r​s​:
		 */
		errorCorrection: string
		/**
		 * O​v​e​r​a​l​l​ ​r​a​t​i​n​g​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		ratingRequired: string
		/**
		 * S​o​m​e​ ​f​i​e​l​d​s​ ​h​a​v​e​ ​v​a​l​i​d​a​t​i​o​n​ ​e​r​r​o​r​s
		 */
		validationErrors: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​s​u​b​m​i​t​ ​r​e​v​i​e​w
		 */
		unableToSubmit: string
		/**
		 * P​l​e​a​s​e​ ​e​n​s​u​r​e​ ​y​o​u​'​r​e​ ​l​o​g​g​e​d​ ​i​n​ ​a​n​d​ ​a​ ​c​a​f​e​ ​i​s​ ​s​e​l​e​c​t​e​d​.
		 */
		ensureLoginAndCafe: string
		/**
		 * R​e​v​i​e​w​ ​U​p​d​a​t​e​d
		 */
		reviewUpdated: string
		/**
		 * R​e​v​i​e​w​ ​S​u​b​m​i​t​t​e​d
		 */
		reviewSubmitted: string
		/**
		 * Y​o​u​r​ ​r​e​v​i​e​w​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​u​p​d​a​t​e​d​.
		 */
		updateSuccess: string
		/**
		 * Y​o​u​r​ ​r​e​v​i​e​w​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​s​u​b​m​i​t​t​e​d​.
		 */
		submitSuccess: string
	}
	cafeDetails: {
		/**
		 * U​s​e​r​ ​R​e​v​i​e​w​s
		 */
		userReviews: string
		/**
		 * W​r​i​t​e​ ​a​ ​R​e​v​i​e​w
		 */
		writeAReview: string
	}
	ratingLabels: {
		/**
		 * B​a​d
		 */
		Bad: string
		/**
		 * P​o​o​r
		 */
		Poor: string
		/**
		 * A​v​e​r​a​g​e
		 */
		Average: string
		/**
		 * G​r​e​a​t
		 */
		Great: string
		/**
		 * E​x​c​e​l​l​e​n​t
		 */
		Excellent: string
	}
}

export type TranslationFunctions = {
	/**
	 * Map of Cafes in DKI Jakarta
	 */
	appDescription: () => LocalizedString
	/**
	 * No Reviews
	 */
	noReviews: () => LocalizedString
	/**
	 * Based on {count} review. 
	 */
	basedOnReviews: (arg: { count: number }) => LocalizedString
	/**
	 * Ratings Breakdown
	 */
	ratingsBreakdown: () => LocalizedString
	/**
	 * Sign Out
	 */
	signOut: () => LocalizedString
	/**
	 * Sign in
	 */
	signIn: () => LocalizedString
	/**
	 * Login to Review
	 */
	loginToReview: () => LocalizedString
	/**
	 * Search...
	 */
	searchCafes: () => LocalizedString
	categories: {
		/**
		 * Ambiance
		 */
		Ambiance: () => LocalizedString
		/**
		 * Work-Friendly
		 */
		'Work-Friendly': () => LocalizedString
		/**
		 * Food & Drinks
		 */
		'Food & Drinks': () => LocalizedString
		/**
		 * Value
		 */
		Value: () => LocalizedString
		/**
		 * Facilities
		 */
		Facilities: () => LocalizedString
		/**
		 * Special Features
		 */
		'Special Features': () => LocalizedString
	}
	attributes: {
		comfort_level: {
			/**
			 * Comfort Level
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Minimal
				 */
				Minimal: () => LocalizedString
				/**
				 * Adequate
				 */
				Adequate: () => LocalizedString
				/**
				 * Comfortable
				 */
				Comfortable: () => LocalizedString
				/**
				 * Luxurious
				 */
				Luxurious: () => LocalizedString
			}
		}
		seating_capacity: {
			/**
			 * Seating Capacity
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Limited
				 */
				Limited: () => LocalizedString
				/**
				 * Moderate
				 */
				Moderate: () => LocalizedString
				/**
				 * Spacious
				 */
				Spacious: () => LocalizedString
			}
		}
		wifi_quality: {
			/**
			 * WiFi Quality
			 */
			name: () => LocalizedString
			options: {
				/**
				 * No WiFi
				 */
				'No WiFi': () => LocalizedString
				/**
				 * Unreliable
				 */
				Unreliable: () => LocalizedString
				/**
				 * Decent
				 */
				Decent: () => LocalizedString
				/**
				 * Fast and Reliable
				 */
				'Fast and Reliable': () => LocalizedString
			}
		}
		outlet_availability: {
			/**
			 * Outlet Availability
			 */
			name: () => LocalizedString
			options: {
				/**
				 * None Visible
				 */
				'None Visible': () => LocalizedString
				/**
				 * Scarce
				 */
				Scarce: () => LocalizedString
				/**
				 * Adequate
				 */
				Adequate: () => LocalizedString
				/**
				 * Plentiful
				 */
				Plentiful: () => LocalizedString
			}
		}
		work_suitability: {
			/**
			 * Work Suitability
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Not Suitable
				 */
				'Not Suitable': () => LocalizedString
				/**
				 * Tolerable
				 */
				Tolerable: () => LocalizedString
				/**
				 * Good
				 */
				Good: () => LocalizedString
				/**
				 * Excellent
				 */
				Excellent: () => LocalizedString
			}
		}
		coffee_quality: {
			/**
			 * Coffee Quality
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Subpar
				 */
				Subpar: () => LocalizedString
				/**
				 * Average
				 */
				Average: () => LocalizedString
				/**
				 * Good
				 */
				Good: () => LocalizedString
				/**
				 * Excellent
				 */
				Excellent: () => LocalizedString
			}
		}
		non_coffee_options: {
			/**
			 * Non-Coffee Options
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Very Limited
				 */
				'Very Limited': () => LocalizedString
				/**
				 * Some Options
				 */
				'Some Options': () => LocalizedString
				/**
				 * Wide Variety
				 */
				'Wide Variety': () => LocalizedString
			}
		}
		food_options: {
			/**
			 * Food Options
			 */
			name: () => LocalizedString
			options: {
				/**
				 * No Food
				 */
				'No Food': () => LocalizedString
				/**
				 * Snacks Only
				 */
				'Snacks Only': () => LocalizedString
				/**
				 * Light Meals
				 */
				'Light Meals': () => LocalizedString
				/**
				 * Full Menu
				 */
				'Full Menu': () => LocalizedString
			}
		}
		price_quality_ratio: {
			/**
			 * Price-Quality Ratio
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Overpriced
				 */
				Overpriced: () => LocalizedString
				/**
				 * Fair
				 */
				Fair: () => LocalizedString
				/**
				 * Good Value
				 */
				'Good Value': () => LocalizedString
				/**
				 * Excellent Value
				 */
				'Excellent Value': () => LocalizedString
			}
		}
		parking_options: {
			/**
			 * Parking Options
			 */
			name: () => LocalizedString
			options: {
				/**
				 * No Parking
				 */
				'No Parking': () => LocalizedString
				/**
				 * Limited Street Parking
				 */
				'Limited Street Parking': () => LocalizedString
				/**
				 * Adequate Parking
				 */
				'Adequate Parking': () => LocalizedString
				/**
				 * Ample Parking
				 */
				'Ample Parking': () => LocalizedString
			}
		}
		cleanliness: {
			/**
			 * Cleanliness
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Needs Improvement
				 */
				'Needs Improvement': () => LocalizedString
				/**
				 * Acceptable
				 */
				Acceptable: () => LocalizedString
				/**
				 * Clean
				 */
				Clean: () => LocalizedString
				/**
				 * Spotless
				 */
				Spotless: () => LocalizedString
			}
		}
		restroom_quality: {
			/**
			 * Restroom Quality
			 */
			name: () => LocalizedString
			options: {
				/**
				 * No Restroom
				 */
				'No Restroom': () => LocalizedString
				/**
				 * Needs Improvement
				 */
				'Needs Improvement': () => LocalizedString
				/**
				 * Acceptable
				 */
				Acceptable: () => LocalizedString
				/**
				 * Clean
				 */
				Clean: () => LocalizedString
				/**
				 * Exceptionally Clean
				 */
				'Exceptionally Clean': () => LocalizedString
			}
		}
		accessibility: {
			/**
			 * Accessibility
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Not Accessible
				 */
				'Not Accessible': () => LocalizedString
				/**
				 * Partially Accessible
				 */
				'Partially Accessible': () => LocalizedString
				/**
				 * Fully Accessible
				 */
				'Fully Accessible': () => LocalizedString
			}
		}
		outdoor_seating: {
			/**
			 * Outdoor Seating
			 */
			name: () => LocalizedString
			options: {
				/**
				 * None
				 */
				None: () => LocalizedString
				/**
				 * Limited
				 */
				Limited: () => LocalizedString
				/**
				 * Ample
				 */
				Ample: () => LocalizedString
			}
		}
		instagram_worthiness: {
			/**
			 * Instagram Worthiness
			 */
			name: () => LocalizedString
			options: {
				/**
				 * Not Particularly
				 */
				'Not Particularly': () => LocalizedString
				/**
				 * Somewhat Photogenic
				 */
				'Somewhat Photogenic': () => LocalizedString
				/**
				 * Very Instagrammable
				 */
				'Very Instagrammable': () => LocalizedString
			}
		}
		pet_friendly: {
			/**
			 * Pet-Friendly
			 */
			name: () => LocalizedString
			options: {
				/**
				 * No
				 */
				no: () => LocalizedString
				/**
				 * Yes
				 */
				yes: () => LocalizedString
			}
		}
	}
	submitReview: {
		/**
		 * Create Review
		 */
		createReview: () => LocalizedString
		/**
		 * Update Review
		 */
		updateReview: () => LocalizedString
		/**
		 * Error uploading image
		 */
		imageUploadError: () => LocalizedString
		/**
		 * Existing images
		 */
		existingImages: () => LocalizedString
		/**
		 * New Images to Upload
		 */
		newImagesToUpload: () => LocalizedString
		/**
		 * New Image
		 */
		newImage: () => LocalizedString
		/**
		 * Please login to create a review 🙏
		 */
		pleaseLogin: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * You have reviewed this cafe
		 */
		userHaveReviewed: () => LocalizedString
		/**
		 * You're modifying your existing review. Update the fields you'd like to change.
		 */
		modifyingExisting: () => LocalizedString
		/**
		 * Fill in the options you'd like to review. Only the overall rating is required.
		 */
		fillOptions: () => LocalizedString
		/**
		 * Overall Rating
		 */
		overallRating: () => LocalizedString
		/**
		 * Select a rating
		 */
		selectRating: () => LocalizedString
		/**
		 * Images
		 */
		images: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Submit Review
		 */
		submit: () => LocalizedString
		/**
		 * Update Review
		 */
		update: () => LocalizedString
		/**
		 * Please correct the following errors:
		 */
		errorCorrection: () => LocalizedString
		/**
		 * Overall rating is required
		 */
		ratingRequired: () => LocalizedString
		/**
		 * Some fields have validation errors
		 */
		validationErrors: () => LocalizedString
		/**
		 * Unable to submit review
		 */
		unableToSubmit: () => LocalizedString
		/**
		 * Please ensure you're logged in and a cafe is selected.
		 */
		ensureLoginAndCafe: () => LocalizedString
		/**
		 * Review Updated
		 */
		reviewUpdated: () => LocalizedString
		/**
		 * Review Submitted
		 */
		reviewSubmitted: () => LocalizedString
		/**
		 * Your review has been successfully updated.
		 */
		updateSuccess: () => LocalizedString
		/**
		 * Your review has been successfully submitted.
		 */
		submitSuccess: () => LocalizedString
	}
	cafeDetails: {
		/**
		 * User Reviews
		 */
		userReviews: () => LocalizedString
		/**
		 * Write a Review
		 */
		writeAReview: () => LocalizedString
	}
	ratingLabels: {
		/**
		 * Bad
		 */
		Bad: () => LocalizedString
		/**
		 * Poor
		 */
		Poor: () => LocalizedString
		/**
		 * Average
		 */
		Average: () => LocalizedString
		/**
		 * Great
		 */
		Great: () => LocalizedString
		/**
		 * Excellent
		 */
		Excellent: () => LocalizedString
	}
}

export type Formatters = {}
